tracbuildbot/htdocs/js/jquery-1.11.1.min.js: removed - not using and fix compatibility with MenusPlugin.
MenusPlugin(http://trac-hacks.org/wiki/MenusPlugin)
error: $.browser.msie Cannot read property 'msie' of undefined.
$.browser was removed from jQuery starting with version 1.9.